/* eslint-disable @typescript-eslint/no-require-imports -- CJS-loadern ersätter endast provets transportmoduler. */
// Avgränsade kontrakts- och regressionsprov; Blob/gateway är kontrollerade transportdubblar.
// Ingen leverantörs- eller hostad E2E-verifiering påstås av denna svit.
const fs = require('node:fs');
const Module = require('node:module');
const ts = require('typescript');
const assert = require('node:assert/strict');
require.extensions['.ts'] = (m, filename) => m._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.CommonJS, esModuleInterop: true } }).outputText, filename);
const docs = new Map(); let seq = 0; let collide = false;
class BlobPreconditionFailedError extends Error {}
const blob = {
 BlobPreconditionFailedError,
 async put(p, body, o) { const old = docs.get(p); if (o.ifMatch && (old?.etag !== o.ifMatch || collide)) { collide = false; throw new BlobPreconditionFailedError(); } if (old && o.allowOverwrite === false) throw new Error('exists'); const etag = '"' + ++seq + '"'; docs.set(p, { body: typeof body === 'string' ? body : Buffer.from(body), etag }); return { etag, pathname: p }; },
 async get(p) { const v = docs.get(p); return v ? { stream: new Response(v.body).body, blob: { etag: v.etag, size: v.body.length, contentType: 'application/octet-stream' } } : null; },
 async del(p) { docs.delete(p); },
 async list({prefix,cursor,limit}) { const keys = [...docs.keys()].filter(k => k.startsWith(prefix)).sort(); const start = Number(cursor || 0); return { blobs: keys.slice(start,start+limit).map(pathname => ({pathname})), hasMore: start+limit < keys.length, cursor: String(start+limit) }; }
};
const originalLoad = Module._load; Module._load = function(id, ...args) { return id === '@vercel/blob' ? blob : originalLoad.call(this,id,...args); };
const A = require('../../lib/arende.ts'), O = require('../../lib/overlamning.ts'), T = require('../../lib/tackning.ts'), I = require('../../lib/intervjuledare.ts'), M = require('../../lib/material.ts'), V = require('../../lib/vy.ts');
const tests = []; const test = (name, fn) => tests.push({name,fn});
let id;
async function arende() { const {a} = await A.skapaArende({kund:{slug:'vikskar-test',namn:'Vikskär TEST'},testdialog:true,ai:'regelstyrd',fakta:[{nyckel:'erbjudande',varde:'Porträtt 45 minuter, 1800 kr',status:'kunden uppger',kalla:'äldre underlag',omrade:'A'}]}); return a; }
function raw(a) { return docs.get('arenden/'+a.id+'.json'); }
function store(a) { const old = raw(a); docs.set('arenden/'+a.id+'.json',{...old,body:JSON.stringify(a)}); }
const input = {kund:{namn:'TEST'},kanda:[],dialog:[],senaste:{fraga_id:'A1',fraga:'Vad?',svar:'Vi måste vänta med publicering tills rekryteringen är offentlig.'},material:0,kandidater:[{id:'B1',omrade:'B',nyckel:'besokare',text:'Vem?',paverkar:'Målgrupp',prio:1,foljd:false}]};
const good = {valda:[{id:'B1',text:'Vem?',typ:'oppen',alternativ:[]}],tackta:[],bild:[],behov:[],meddelande:'Tack.',klar:false};
test('Officiellt strukturerat kontrakt och utanför-banken-citat valideras semantiskt', () => { assert.equal(I.JSON_SCHEMA.additionalProperties,false); assert(I.JSON_SCHEMA.required.includes('behov')); assert(I.validera(good,input)); assert.equal(I.validera({...good,valda:[{...good.valda[0],id:'HITTEPA'}]},input),null); assert.equal(I.validera({...good,behov:[{nyckel:'sarskilt',citat:'påhittad text',fraga:'Vad?'}]},input),null); assert(I.validera({...good,behov:[{nyckel:'publicering',citat:input.senaste.svar,fraga:'Vem godkänner?'}]},input)); });
test('Befintliga ämnen skapas inte igen med påhittat suffix; ett nytt källbundet ämne behålls',()=>{const r=I.validera({...good,behov:[{nyckel:'besokare_fejl',citat:input.senaste.svar,fraga:'Vem?'},{nyckel:'publiceringskoppling',citat:input.senaste.svar,fraga:'Hur kopplas underlaget till rätt uppdrag?'}]},input);assert.equal(r.behov.length,1);assert.equal(r.behov[0].nyckel,'publiceringskoppling');});
test('Avkortat/refusal/format särskiljs och förbrukade token bevaras', () => { for (const [reason,klass] of [['length','avkortat'],['content_filter','vagran'],['stop','format']]) assert.throws(() => I.lasGatewaySvar({choices:[{finish_reason:reason,message:{content:'{'}}],usage:{completion_tokens:1500}}),e=>e.klass===klass&&e.tokens_out===1500); });
test('Gateway avkortning återförsöks högst en gång med högre ändlig budget och samma modell', async () => { process.env.AI_GATEWAY_API_KEY='test'; let calls=[]; global.fetch=async(url,opt)=>{ calls.push(JSON.parse(opt.body)); return new Response(JSON.stringify(calls.length===1?{choices:[{finish_reason:'length',message:{content:'{'}}],usage:{completion_tokens:4000}}:{choices:[{finish_reason:'stop',message:{content:JSON.stringify(good)}}],usage:{completion_tokens:300}})); }; const r=await I.ledNasta(input,'gateway','openai/gpt-5-mini');assert(!r.fallback);assert.equal(r.forsok,2);assert.equal(r.tokens_out,4300);assert(calls.every(c=>c.model==='openai/gpt-5-mini'&&c.response_format.json_schema.strict));assert.equal(calls[0].max_completion_tokens,4000);assert.equal(calls[1].max_completion_tokens,8000); });
test('Permanenta HTTP-fel återförsöks inte; trasigt/semantiskt svar blir sann reservstatus', async () => { let count=0;global.fetch=async()=>{count++;return new Response('{}',{status:403});};let r=await I.ledNasta(input,'gateway','openai/gpt-5-mini');assert.equal(count,1);assert.equal(r.felklass,'atkomst_eller_kontrakt'); global.fetch=async()=>{count++;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...good,valda:[]})}}]}));};r=await I.ledNasta(input,'gateway','openai/gpt-5-mini');assert(r.fallback);assert.equal(r.felklass,'sakligt_otillrackligt');assert.equal(r.forsok,2); });
test('Täckning skiljer outrett, vet inte, ej tillämpligt och saknad åtkomst', async()=>{const a=await arende();assert(T.tackning(a).some(t=>t.status==='inte_undersokt'));for(const [ix,typ] of ['vet_inte','ej_tillampligt','atkomst_saknas'].entries()){const f=require('../../lib/bank.ts').BANK.grund[ix];a.svar.push({fraga_id:f.id,nyckel:f.nyckel,typ,text:typ,revision:2,mottaget:A.nu(),idempotens:'TESTKEY'+ix});}const statuses=T.tackning(a).map(t=>t.status);assert(statuses.includes('kunden_vet_inte'));assert(statuses.includes('inte_tillampligt'));assert(statuses.includes('atkomst_saknas'));});
test('Flertematiskt kundsvar följs över fält och 45→60 blir senare kundord',async()=>{const a=await arende();a.fragor.push({id:'BET1',nyckel:'betalning_vad',omrade:'C',text:'Betalning?',paverkar:'Pris',typ:'oppen',kalla:'bank',omgang:1,stalld:A.nu(),status:'stalld',valjare:'regelstyrd'});store(a);const {a:b}=await A.registreraSvar(a.id,{fraga_id:'BET1',text:'Rättelse: porträttsessionen är numera 60 minuter, samma pris. Vi delar samma rum och ljusutrustning. Bilder får inte visas innan rekryteringen är offentlig. Vi behöver påminnelser och Google Ads.',typ:'text',idempotens:'TEMANSVAR1'});assert.equal(b.behov.length,4);assert(A.bild(b).find(f=>f.nyckel==='erbjudande').varde.includes('60 minuter'));assert(A.kandidater(b).some(k=>k.nyckel==='publiceringsvillkor'));});
test('Signal skapas atomärt, dubbel inlämning ingen dubblett, gammal kvittens stänger aldrig ny ändring',async()=>{let a=await arende();id=a.id;a=await A.lamnaIn(a.id);const old=a.signal;const again=await A.lamnaIn(a.id);assert.equal(again.signal.id,old.id);await O.kvittera(id,{signal_id:old.id,revision:old.revision,utforare:'digitala/test',import_sha256:'a'.repeat(64)});assert(!(await O.signaler()).signaler.some(x=>x.arende_id===id));await A.registreraRattelse(id,{nyckel:'erbjudande',varde:'60 minuter',idempotens:'RATTELSE1'});const ny=(await A.lasArende(id)).signal;assert.notEqual(ny.id,old.id);await O.kvittera(id,{signal_id:old.id,revision:old.revision,utforare:'digitala/test',import_sha256:'a'.repeat(64)});assert((await O.signaler()).signaler.some(x=>x.id===ny.id));await assert.rejects(O.kvittera(id,{signal_id:old.id,revision:old.revision,utforare:'digitala/test',import_sha256:'b'.repeat(64)}),e=>e.status===409);});
test('ETag-konflikt återläses; konkurrerande kvittenser kan inte ersätta varandra',async()=>{const a=await A.lasArende(id);collide=true;const p={signal_id:a.signal.id,revision:a.signal.revision,utforare:'digitala/test',import_sha256:'b'.repeat(64)};await O.kvittera(id,p);await O.kvittera(id,p);assert.equal((await A.lasArende(id)).kvittenser.filter(k=>k.signal_id===p.signal_id).length,1);await assert.rejects(O.kvittera(id,{...p,utforare:'annan'}),e=>e.status===409);});
test('Returfråga med revision/idempotens återkommer i samma dialog; svar skapar ny signal',async()=>{const a=await A.lasArende(id);const p={idempotens:'RETURKEY1',bas_revision:a.revision,utforare:'digitala/test',fragor:[{nyckel:'buffert',text:'Hur mycket buffert behövs mellan två fotograferingar?',paverkar:'Bokningens resursregler'}]};let b=await O.returfragor(id,p);assert(V.tillVy(b).oppna.some(f=>f.text===p.fragor[0].text));assert(!V.tillVy(b).arende.inlamnad);await O.returfragor(id,p);assert.equal((await A.lasArende(id)).returfragor.length,1);await assert.rejects(O.returfragor(id,{...p,idempotens:'RETURKEY2'}),e=>e.status===409);b=(await A.registreraSvar(id,{fraga_id:b.returfragor[0].fragor[0],typ:'text',text:'15 minuter',idempotens:'RETURSVAR1'})).a;assert.equal(b.signal.revision,b.revision);assert(A.exportPaket(b).svar.some(s=>s.text==='15 minuter'));});
test('HTML original och textutdrag hålls isär; aktiv kod körs aldrig; läskvittens är explicit hashbunden',async()=>{const html=Buffer.from('<html><script>fetch("https://evil.example")</script><p>Porträtt 45 minuter</p></html>');const sha=require('node:crypto').createHash('sha256').update(html).digest('hex');assert(M.identifiera('gammal.html',html));const x=M.extrahera('text/html',html,sha);assert(!x.text.includes('fetch'));assert(x.text.includes('45 minuter'));let {a}=await A.laggMaterialFil(id,{filnamn:'gammal.html',mime:'text/html',data:html.buffer.slice(html.byteOffset,html.byteOffset+html.byteLength),sha256:sha,idempotens:'MATERIAL1'});const m=a.material[0];assert.equal(A.exportPaket(a).material[0].lasstatus,'extraherad');await assert.rejects(O.materialLast(id,m.id,{sha256:'f'.repeat(64),utforare:'digitala/test',resultat:'Läst gamla priser'}),e=>e.status===409);a=await O.materialLast(id,m.id,{sha256:sha,utforare:'digitala/test',resultat:'Läst gammal tidsuppgift. Senare kundrättelse har företräde.'});assert.equal(A.exportPaket(a).material[0].lasstatus,'last');assert.equal(raw(a).body.includes('fetch'),false);assert(Buffer.from(docs.get(m.blob).body).equals(html));});
test('Modellresultat under sen kundrättelse kasseras utan att skriva över aktuella ord',async()=>{const a=await arende();a.ai.lage='gateway';store(a);global.fetch=async()=>{await A.registreraRattelse(a.id,{nyckel:'erbjudande',varde:'Porträtt 75 minuter, aktuellt kundbesked',idempotens:'SENRATTELSE'});return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({...good,valda:[{id:'A1',text:'Vad är målet?',typ:'oppen',alternativ:[]}],bild:[{nyckel:'erbjudande',varde:'45 minuter'}]})}}]}));};await A.nasta(a.id);const b=await A.lasArende(a.id);assert.equal(A.bild(b).find(f=>f.nyckel==='erbjudande').varde,'Porträtt 75 minuter, aktuellt kundbesked');assert(b.handelser.some(h=>h.typ==='nasta_forkastad'));assert(!b.fakta_ai.some(f=>f.giltig&&f.varde==='45 minuter'));});
test('Kundvy visar pausat/reserv efter omladdning, aldrig ett falskt AI på',async()=>{const a=await arende();a.ai.lage='gateway';a.ai.aktuell='reserv';assert.equal(V.tillVy(a).ai.status,'reserv');a.ai.paus_till=new Date(Date.now()+60000).toISOString();assert.equal(V.tillVy(a).ai.status,'pausad');});
test('Dubbla samtidiga filinlämningar ger ett aktivt original även vid olika idempotensnycklar', async()=>{const a=await arende(); const data=Buffer.from('Samma kontrollerade kundunderlag');const sha=require('node:crypto').createHash('sha256').update(data).digest('hex');const arg={filnamn:'underlag.txt',mime:'text/plain',data:data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),sha256:sha};await Promise.all([A.laggMaterialFil(a.id,{...arg,idempotens:'SAMTIDIG1'}),A.laggMaterialFil(a.id,{...arg,idempotens:'SAMTIDIG2'})]);const b=await A.lasArende(a.id);assert.equal(b.material.length,1);});
test('Signalpagination tappar inte en komplettering vid nästa fulla scan',async()=>{for(let n=0;n<102;n++){const a=await arende();await A.lamnaIn(a.id);}let cursor;const seen=new Set();do{const page=await O.signaler(cursor);for(const s of page.signaler)seen.add(s.id);cursor=page.cursor;}while(cursor);assert(seen.size>=102);const a=await A.lasArende(id);await A.registreraRattelse(id,{nyckel:'erbjudande',varde:'Aktuell omfattning 90 minuter',idempotens:'EFTERSCAN'});let found=false;cursor=undefined;do{const page=await O.signaler(cursor);found ||= page.signaler.some(s=>s.arende_id===a.id&&s.revision>a.signal.revision);cursor=page.cursor;}while(cursor);assert(found);});
(async()=>{const result=[];for(const t of tests){try{await t.fn();result.push({namn:t.name,ok:true});console.log('PASS',t.name);}catch(e){result.push({namn:t.name,ok:false,fel:e.stack});console.error('FAIL',t.name,e);}}const receipt={tid:new Date().toISOString(),omfattning:'Avgränsade domän- och transportkontrakt med kontrollerade providerersättare. Inte leverantörsprov.',resultat:result,complete:result.every(r=>r.ok)};if(process.env.KUNDSTART_PROVKVITTO)fs.writeFileSync(process.env.KUNDSTART_PROVKVITTO,JSON.stringify(receipt,null,2));process.exit(receipt.complete?0:1);})();
